---
kind: pipeline
name: yaml-validator

steps:
  - name: yaml-validator
    image: python:3.7.4-alpine3.10
    commands:
      - pip install --user yamllint --no-warn-script-location --upgrade pip
      - /root/.local/bin/yamllint -c /drone/src/.yamllint .drone.yml

trigger:
  event:
    - pull_request

---
kind: pipeline
name: slack-send-pr

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: trainee21-slack-bot-pr
      template: >
        {{#success build.status}}
          @here Please review on https://github.com/atgse/trainee21-frontend/pull/{{build.pull}}
          Author: {{build.author}}
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
trigger:
  event:
    - pull_request

---
kind: pipeline
name: pr-trainee21-frontend
type: docker

node:
  instance: highmemory

platform:
  os: linux
  arch: amd64

steps:
  - name: generate-semver
    pull: always
    image: 146546704593.dkr.ecr.eu-west-1.amazonaws.com/plugins/semver:latest
    settings:
      github_token:
        from_secret: sonar_github_token
      start_tag: 0.0.0
      pre_release: true

  - name: build-node.js-trainee21-frontend
    image: node:12-alpine
    commands:
      - npm cache clean --force
      - mkdir -p build-artifacts
      - npm install express --save
      - npm install -g nodemon
      - npm install install pug
      - cp package*.json build-artifacts
      - cp -rf ./frontend build-artifacts
      - ls build-artifacts
    depends_on:
      - generate-semver

  - name: build-docker
    image: plugins/ecr:latest
    settings:
      build_args:
        - trainee21-frontend_version=0.0.1
      context: /drone/src/build-artifacts
      create_repository: true
      dockerfile: Dockerfile
      force_tag: true
      region: eu-west-1
      registry: 146546704593.dkr.ecr.eu-west-1.amazonaws.com
      repo: trainee21-frontend
      env_file: /drone/src/.semver
      build_args_from_env: SEMVER_NEW_VERSION
    depends_on:
      - build-node.js-trainee21-frontend
      - generate-semver

  - name: trainee21-frontend
    image: 146546704593.dkr.ecr.eu-west-1.amazonaws.com/trainee21-frontend:0.0.${DRONE_BUILD_NUMBER}-intpr${DRONE_PULL_REQUEST}.${DRONE_BUILD_CREATED}
    detach: true
    depends_on:
      - build-docker

trigger:
  event:
    - pull_request
image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
name: ci-trainee21-frontend
type: docker

node:
  instance: highmemory

platform:
  os: linux
  arch: amd64

steps:

  - name: generate-semver
    pull: always
    image: 146546704593.dkr.ecr.eu-west-1.amazonaws.com/plugins/semver:latest
    settings:
      github_token:
        from_secret: sonar_github_token
      start_tag: 0.0.0

  - name: build-node.js-trainee21-frontend
    image: node:12-alpine
    commands:
      - npm cache clean --force
      - mkdir -p build-artifacts
      - npm install express --save
      - npm install -g nodemon
      - npm install install pug
      - cp package*.json build-artifacts
      - cp -rf ./frontend build-artifacts
      - ls build-artifacts
    depends_on:
      - generate-semver

  - name: build-docker
    image: plugins/ecr:latest
    settings:
      context: /drone/src/build-artifacts
      create_repository: true
      dockerfile: Dockerfile
      force_tag: true
      region: eu-west-1
      registry: 146546704593.dkr.ecr.eu-west-1.amazonaws.com
      repo: trainee21-frontend
      env_file: /drone/src/.semver
      build_args_from_env: SEMVER_NEW_VERSION
    depends_on:
      - build-node.js-trainee21-frontend

  - name: release-to-nexus
    image: plugins/docker:latest
    settings:
      context: /drone/src/build-artifacts
      dockerfile: Dockerfile
      force_tag: true
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password
      region: eu-west-1
      registry: nexus.hh.atg.se:17001
      repo: nexus.hh.atg.se:17001/releases/trainee21-frontend
      env_file: /drone/src/.semver
      build_args_from_env: SEMVER_NEW_VERSION
    depends_on:
      - build-docker

trigger:
  branch:
    - master
  event:
    - push

---
kind: secret
name: maven_username

get:
  path: prod/maven
  name: username

---
kind: secret
name: maven_password

get:
  path: prod/maven
  name: password

---
kind: secret
name: sonar_token

get:
  path: prod/sonar
  name: token


---
kind: secret
name: sonar_github_token

get:
  path: atgsebot/github
  name: sonar

---
kind: secret
name: nexus_username

get:
  path: push/nexus
  name: username

---
kind: secret
name: nexus_password

get:
  path: push/nexus
  name: password

---
kind: secret
name: dockerhub_pull_credentials
get:
  path: prod/drone-config
  name: dockerhub_pull_credentials
